### ISSUE TITLE
Notifications plugin won't load: Argument 'object' (type interface) may not be null

### ISSUE THREAD

**Issue by EvilJimJafar** [andyholmes/gnome-shell-extension-gsconnect#246]
Plugin won't load:

_init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/notification.js:77:9
loadPlugin@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:783:26
loadPlugins@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:808:19
async*vfunc_startup/<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:746:13
vfunc_startup@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:743:9
_init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:97:9
@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:863:2

**Comment by treba123** [comment]
Same here, fedora 29, gnome-shell 3.30.1.1

**Comment by andyholmes** [comment]
Could you try with this ZIP:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2496021/gsconnect.andyholmes.github.io.zip)

See [Installing from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip)

**Comment by treba123** [comment]
Solves the problem for me

**Comment by AGitBoy** [comment]
I'm using that ZIP on Ubuntu 18.10, and this same problem occurs for me as well. I'm on GNOME 3.30.1

**Comment by andyholmes** [comment]
You're using the Zip posted in this thread? If so, what has the error message changed to?

**Comment by EvilJimJafar** [comment]
> What version of GNOME Shell are you running?

3.30.1 here running on Manjaro.

**Comment by AGitBoy** [comment]
No change in error message. I'll try rebooting and reninstalling the plugin.

**Comment by AGitBoy** [comment]
After rebooting and reinstalling the extension, it no longer gives me the error message.

**Comment by pauloxnet** [comment]
It worked for me on Ubuntu 18.04.1 LTS and Gnoem 3.28.2

The correct link for the "Install from Zip" section is https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip

**Comment by andyholmes** [comment]
Thanks, I forgot I moved that some days ago.

**Comment by pwd-github** [comment]
Had this the first time, it seems to all be working fine now.

**Comment by mdziekon** [comment]
Same problem happened for me when updated to the latest "Gnome Extensions" provided version. Same problem happened on both (two different computers):
- Ubuntu 18.04.1 LTS (GNOME Shell 3.28.3)
- Ubuntu 18.10 (GNOME Shell 3.30.1)

**Comment by ferdnyc** [comment]
(Per @andyholmes , that referenced commit 41c96a5 is the fix for this issue, the one included in the zip file above.)

**Comment by odinho** [comment]
Is there a way to revert the gnome extension notification? I just clicked this too now, and got this message. Or indeed release the new version with the fix :)

**Comment by Eonfge** [comment]
Confirmed, running on Ubuntu 18.04 LTS.

I updated from 12 to 13, and then it was done.

**Comment by andyholmes** [comment]
> Is there a way to revert the gnome extension notification? I just clicked this too now, and got this message. Or indeed release the new version with the fix :)

I was planning on waiting until v13 was reviewed to make it easier on the reviewers, but after upgrading my distribution I forgot to re-install my email client and didn't see it was already reviewed!

I now have a million e-mails to sort/prioritize, and some unpolished changes to clean up before release, but I'll try and get this out ASAP for you all!

**Comment by ferdnyc** [comment]
This turned out to have been a one-time failure, at least on Fedora 28 — when I upgraded to v13 via extensions.gnome.org, I hit the reported error (and GSConnect was non-functional), but following a system reboot v13 is working fine for me again.

**Comment by nsrosenqvist** [comment]
This happened to me too after upgrading to v13. Wasn't the fix supposed to have been included in the latest release?

**Comment by ferdnyc** [comment]
> This happened to me too after upgrading to v13. Wasn't the fix supposed to have been included in the latest release?

I don't _believe_ so. My understanding of the timeline is that v13 was where people first encountered the bug. The fix will be part of v14 which hasn't been released yet.

**Comment by andyholmes** [comment]
Correct, this is fixed in the Zip above but not v13. I'm still not sure why this happens, possibly some weird race condition, but most users have reported it's fixed after a single restart of the service anyways.

**Comment by nsrosenqvist** [comment]
Ok, that's great, thank you!

**Comment by ferdnyc** [comment]
Maybe it's worth submitting a v14 to e.g.o with _just_ that fix, though, to get the upgrade path corrected for people, and confirm the fix is successful. Then the next release can be v15, and contain all the substantive changes that have been made since, without having to worry about this issue.

**Comment by Tids** [comment]
+1 for the Idea to release v14 with just that fix and as soon as possible.
I was with a broken gsconnect because of gnome 3.30 and had to wait for the v14 just so that i'm now with a broken gsconnect and have to wait for v14. On the user side thats really frustrating.

```
_init@/home/fabian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/notification.js:77:9
loadPlugin@/home/fabian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:783:26
loadPlugins@/home/fabian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:808:19
async*vfunc_startup/<@/home/fabian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:747:13
vfunc_startup@/home/fabian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:9
_init@/home/fabian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:97:9
@/home/fabian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:864:2
```

**Comment by ferdnyc** [comment]
:+1: I believe v14 has already been submitted to e.g.o with the upgrade-crasher fix.

**Comment by ferdnyc** [comment]
(However, if you... well, at a maximum, completely restart your computer, you should find that v13 becomes functional. It breaks on _upgrade_ from v12, but is actually functional after that point. At least, that's been most of our experience.)

**Comment by pwd-github** [comment]
Sorry, I'm confused. Given the v13 works after the initial failure notification, what is with the rush to get v14 out?

**Comment by ferdnyc** [comment]
To stop upgraders getting hit with initial failure notifications.

**Comment by Tids** [comment]
@ferdnyc no. After restarting it's just the same. I'm unable to use V13 at this point. Restarting does not fix it.

**Comment by andyholmes** [comment]
That would still be v13, if you got it from extensions.gnome.org. v14 with that fix is available on the [releases page](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/latest).

**Comment by ferdnyc** [comment]
> @ferdnyc no. After restarting it's just the same. I'm unable to use V13 at this point. Restarting does not fix it.

Apologies @Tids , dropped the ball on responding to this sooner.

This is (AFAIK) the first we're hearing of v13 still not working after a restart, so perhaps you're encountering some other (or, additional) bug. (It also means v14 may not solve this for you, anyway.)

Can you run:
```sh
journalctl --user -b -g gsconnect
``` 
("display all user journal entries  since the last reboot containing 'gsconnect'"), and see if there are any error messages output when Gnome Shell tries to start the extension? The lines will be long, so you may want to add ` --no-pager` so it'll wrap them instead of making you scroll horizontally.

That output _may_ contain personal information (though probably not, if GSConnect is failing to even start), so posting the entire contents may not be wise. Just copy-pastes of anything that looks interesting or important should be fine, at least for starters.

**Comment by andyholmes** [comment]
Closing this since v15 has been reviewed.
