### ISSUE TITLE
Mount Issues in Gnome 3.36

### ISSUE THREAD

**Issue by avantbored** [andyholmes/gnome-shell-extension-gsconnect#801]
OS: Manjaro Linux 19.0.2
DE: Gnome 3.36
Kernel: 5.4.27-1-MANJARO
Device (Laptop): Dell XPS 13 9370
Device (phone): Samsung Galaxy S9

**Issue: Issues with mounting mobile device to laptop**

Please see attached log (copy + pasting was making this unreadable).
[gsconnect_log_avantbored_3.2920.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4400025/gsconnect_log_avantbored_3.2920.txt)

**Comment by ferdnyc** [comment]
There is only a single log message in there from GSConnect, and it logs the normal `startBrowsing` request sent from the computer to the device.

Literally every other line there appears to be connection-state updates from either your WiFi interface or your Bluetooth device(s). (Which, if your network is that volatile, may explain the mount  issues — SFTP is not a forgiving protocol.)

When you say there are "issues", that's a litte vague. Can you explain what kind of issues? There are no logs of any issues in what you supplied, and we're bad at guessing.

**Comment by avantbored** [comment]
Apologies for the vagueness.

1) My phone is not showing up in the list of available devices to browse in Nautilus. 

2) There's a lot of bluetooth at my desk these days. 

Ryan

**Comment by andyholmes** [comment]
This seems like it's probably another case of KDE Connect just not responding. If GSConnect sends the `startBrowsing` packet and KDE Connect just doesn't respond, there's nothing that can really be fixed in GSConnect.

Maybe try force-stopping the app and re-opening it.

**Comment by avantbored** [comment]
Thank you for the suggestion. 

I first tried your suggestion, but did not change anything. My device still does not appear in Nautilus. 

Secondly, I tried unpairing, and then clearing KDE Connect's app data. My device still does not show up in Nautilus.

**Comment by andyholmes** [comment]
If you're still not getting a response packet in the log, it sounds like something really funky is happening in the Android app. You're sure it's not sending a `kdeconnect.sftp` packet back?

**Comment by avantbored** [comment]
I've included another log; I see `kdeconnect.sftp` going only one way. 


[gsconnect.37BPI0.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4432007/gsconnect.37BPI0.txt)

**Comment by andyholmes** [comment]
That seems like kdeconnect-android is correctly responding with the SFTP login information. You'll have to find what the actual error is.

If the mount operation fails, GSConnect will print an proper error to the log. If it happens later inside GVfs, there should still be a message somewhere in the journal indicating why the mount failed.

**Comment by avantbored** [comment]
ok, i'll investigate. 

I've never accessed the journal before, so I will have to write back once I figure out how to.

thank you.

**Comment by andyholmes** [comment]
Looks pretty much the same :)

Basically what you'll want to do is search using GNOME Logs, or just have `journalctl -f -o cat` running in terminal, to see what is actually going wrong. Searching for "gvfs", "sftp" or something like that.

In the logs you're providing, there's not actually anything going wrong, so it's hard to recommend what to do.

**Comment by avantbored** [comment]
Thanks for that. 

Running the `journalctl` command provided, the only entry for `gvfs` I see is its initialization: 

`# _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’`

**Comment by andyholmes** [comment]
I guess the next step is to debug Gvfs directly:

```sh
$ pkill gvfs; pkill nautilus
$ GVFS_DEBUG=1 $(find /usr/lib* -name gvfsd 2>/dev/null) --replace
```
Once that's running in a terminal, try to mount the device and you should see messages like this:

```
sftp: Added new job source 0x560ae67a3080 (GVfsBackendSftp)
sftp: Queued new job 0x560ae6784730 (GVfsJobMount)
sftp: spawn_ssh: /usr/bin/ssh -oForwardX11 no -oForwardAgent no -oPermitLocalCommand no -oClearAllForwardings yes -oProtocol 2 -oNoHostAuthenticationForLocalhost yes -p 1755 -s 192.168.1.68 sftp 
sftp: handle_login #1 initial_connection = 1 - user: (null), host: 192.168.1.68, port: 1755
sftp: handle_login #1 - password_save: 0
sftp: handle_login #1 - ret_val: 1
sftp: spawn_ssh: /usr/bin/ssh -oForwardX11 no -oForwardAgent no -oPermitLocalCommand no -oClearAllForwardings yes -oProtocol 2 -oNoHostAuthenticationForLocalhost yes -p 1755 -s 192.168.1.68 sftp 
sftp: handle_login #2 initial_connection = 0 - user: (null), host: 192.168.1.68, port: 1755
sftp: handle_login #2 - ret_val: 1
sftp: send_reply(0x560ae6784730), failed=0 ()
```

**Comment by avantbored** [comment]
First: Thank you for your help with this. I hope you're doing well in the chaos of the pandemic. 
Secondly, something very strange has happened. There is no output when I run the debug commands provided. 

I googled quickly `GvfsBackendSftp`, and saw there were some issues of missing packages with nautilus. 

This is really strange, because before I upgraded my Manjaro machine to GNOME 3.36, mounting and browsing with nautilus was not an issue.

**Comment by andyholmes** [comment]
Hmm, that is strange. I think that's one of the built-in backends, but maybe try re-installing those packages and see if it fixes it?

**Comment by avantbored** [comment]
I reinstalled `gvfs` from the manjaro `extra` repositories, but it did not solve this issue.

I searched for the `sftp` file specifically in `/usr/lib`, found `gvfsd-sftp`, but the contents were empty.

**Comment by andyholmes** [comment]
I think `gvfsd-sftp` should be a binary, but if that's not the case you'll probably want to open an issue with the package maintainer for Manjaro (or Arch).

**Comment by Grizzlywolf** [comment]
I have the same issue, pressing Mount does nothing, log shows nothing. Manjaro Gnome and Xiaomi Mi8 with Android 10.

**Comment by andyholmes** [comment]
This seems like it's bug in Manjaro, so someone will have to file an upstream bug report to get the ball rolling.

**Comment by andyholmes** [comment]
As discovered by @Srinivasa314 in #816, this is caused by `openssh` deprecating particular host keys. The reason this only affects Arch/Manjaro is that everyone else seems to compile against `libgcrypt`.

There is an upstream patch, which should be released in Google Play/F-Droid soon-ish.

**Comment by andyholmes** [comment]
Should be fixed now in kdeconnect-android 1.14, available on Google Play now.
