### ISSUE TITLE
CLI interface return errors when used to send sms

### ISSUE THREAD

**Issue by deejy** [andyholmes/gnome-shell-extension-gsconnect#813]
Ubuntu 20.04 LTS, gsconnect v36 (see also infra)

**Describe the bug**
The CLI is OK with my phone using the --ring option, the --ping and also to transfer files using --share-file.
However, trying to send sms doesn't work

**Steps To Reproduce:**
1- cd ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service
2- using the comandeline : ./daemon.js --device=abcdefg0123456789 --message=0722222222 --message-body='Hello' " 

**Give the following error message**
(GSConnect:7595): Gjs-WARNING **: 19:58:14.035: JS ERROR: Error: Expected type utf8 for Argument 'string' but got type 'Array'
_packVariant@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:104:29
_packVariant@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:163:27
_init/this.Variant._new_internal@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:298:23
_init/this.Variant.new@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:307:16
_cliMessage@./daemon.js:976:53
vfunc_handle_local_options@./daemon.js:1085:22
@./daemon.js:1120:17

**Support Log**

No error reported in the generated Log

**System Details :**

 - **GSConnect version:** V36
  - **Installed from:** available in the new ubuntu distro but activated from GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Ubuntu 20.04 freshly upgraded for the purpose of using gsconnect!

**GSConnect environment :**

 - **Paired Device(s):** Doogee N20
 - **KDE Connect app version:** 1.13.6
 - **Plugin(s):** 

**Additional Notes:**

The linking procedure given in the [CLI documentation ](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/CLI-Scripting) seems  irrelevant : it links the directory, not the executable. However using such link instead of the whole path to the daemon.js script also gives errors (an other bug to document?...;-)

**Comment by andyholmes** [comment]
Thanks for reporting, should be fixed in b60cd0a. I've removed the documentation section describing how to adjust `PATH` since it seems to break GSConnect's bootstrapping if the CWD is changed.

**Comment by jvelez88** [comment]
Bug still present (GSConnect 28:

~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service$ ./daemon.js --device=bc7c42a5ae6605b2 --message=5523032048 --message-body="hello"

(GSConnect:31882): Gjs-WARNING **: 16:52:19.797: JS ERROR: Error: Expected type utf8 for Argument 'string' but got type 'object'
_pack_variant@resource:///org/gnome/gjs/modules/overrides/GLib.js:103:9
_pack_variant@resource:///org/gnome/gjs/modules/overrides/GLib.js:150:20
_init/this.Variant._new_internal@resource:///org/gnome/gjs/modules/overrides/GLib.js:260:16
_init/this.Variant.new@resource:///org/gnome/gjs/modules/overrides/GLib.js:269:9
_cliMessage@./daemon.js:1005:40
vfunc_handle_local_options@./daemon.js:1114:17
@./daemon.js:1149:2

**Comment by andyholmes** [comment]
This bug was fixed and released in v37. v28 and older versions of GNOME are not supported, so you will either have to upgrade your desktop or backport the patch in b60cd0a yourself to benefit from the fix.
